[package]
name = "ultimo-teste"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.1.0", features = ["sqlite", "r2d2"] }
rand = "0.8"
argon2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"

